const API_KEY = "YOUR_API_KEY";
const AUTH_DOMAIN = "YOUR_AUTH_DOMAIN";
const DATABASE_URL = "YOUR_DATABASE_URL";
const PROJECT_ID = "YOUR_PROJECT_ID";
const STORAGE_BUCKET = "YOUR_STORAGE_BUCKET";
const MESSSAGING_SENDER_ID = "YOUR_MESSAGING_SENDER_ID";
const APP_ID = "YOUR_APP_ID";
const MEASUREMENT_ID = "YOUR_MEASUREMENT_ID";

export {
  API_KEY,
  AUTH_DOMAIN,
  DATABASE_URL,
  PROJECT_ID,
  STORAGE_BUCKET,
  MESSSAGING_SENDER_ID,
  APP_ID,
  MEASUREMENT_ID
};
